language: csharp

os:
  - osx
  - linux

dist: trusty

addons:
  apt:
    packages: 
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

sudo: required

mono: none

dotnet: 1.0.1

script:
  - ./build.sh --quiet verify
