on:
  release:
    types: [published]

  jobs:
    build:
      runs-on: ubuntu-18.04
      name: Publish NuGet Packages
      steps:

        # Checkout
        - name: Checkout repository
          uses: actions/checkout@v2

        # Setup .NET Core
        - name: Setup .NET Core @ Latest
          uses: actions/setup-dotnet@v1
          with:
            source-url: https://nuget.pkg.github.com/piranhacms/index.json
          env:
            NUGET_AUTH_TOKEN: ${{secrets.NugetAuthToken}}

        # Restore packages
        - name: NPM Install
          run: |
            cd core/Piranha.Manager
            npm install
            cd ../../

        # Build and pack
        - name: Build solution and generate NuGet package
          run: ./pack.sh

        # Install SignClient
        - name: Install SignClient
          run: dotnet tool install --tool-path . SignClient

        # Sign packages
        - name: Sign packages
          run: SignClient "SIGN" --input "artifacts/*.nupkg" --config "sign.json" --user "${{secrets.SignClientUser}}" --secret "${{secrets.SignClientSecret}}" --name "Piranha" --description "Piranha" --descriptionUrl "https://github.com/piranhacms/piranha.core"

        # Sign symbol packages
        - name: Sign packages
          run: SignClient "SIGN" --input "artifacts/*.snupkg" --config "sign.json" --user "${{secrets.SignClientUser}}" --secret "${{secrets.SignClientSecret}}" --name "Piranha" --description "Piranha" --descriptionUrl "https://github.com/piranhacms/piranha.core"

        # Push to NuGet
        # - name: Push generated package to GitHub registry
        #   run: dotnet nuget push **/*.nupkg --skip-duplicate